import Head from "next/head";
import Image from "next/image";
import { GraphQLClient, gql } from "graphql-request";
import styles from "../styles/Home.module.css";

const hygraph = new GraphQLClient(process.env.HYGRAPH_CONTENT_API);

const QUERY = gql`
  {
    posts {
      id
      title
      datePublished
      slug
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      coverPhoto {
        publishedAt {
          createdBy {
            id
          }
          url
        }
      }
    }
  }
`;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}></main>
    </div>
  );
}
